import type { Metadata } from "next";
import {
  Cormorant_Garamond,
  Inter,
  Poppins,
} from "next/font/google";

import "./globals.css";

import Footer from "@/components/ui/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { getCurrentUser } from "@/lib/auth";
import MobileNavigation from "@/components/ui/MobileNavigation";
import { Toaster } from "sonner";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // pick the weights you actually use
  variable: '--font-poppins',
  display: 'swap',
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Urban Loom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html
      lang="en"
      className={`${inter.variable} ${cormorant.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="font-body min-h-screen relative">
        <AuthProvider user={user}>
          <div className="min-h-screen flex flex-col justify-between w-full">
            <div>
              <MobileNavigation user={user} />
            </div>

            <div className="flex min-h-screen w-full">
              {children}
            </div>

            <Footer />
            <Toaster position="top-right" richColors />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
