import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { getCurrentUser } from "@/lib/auth";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   weight: ["300", "400", "500", "600", "700"],
//   style: ["normal"],
//   subsets: ["latin"],
// });

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Urban Loom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getCurrentUser();
  return (
    <html
      lang="en"
      className={`${inter.variable} ${cormorant.variable} h-full antialiased`}
    >
      <body className="font-body">
        <AuthProvider user={user}>
          <div className="min-h-full flex flex-col justify-between  w-full m-auto">
            <div className="">
              <Header />
            </div>
            <div className="flex m-auto">{children}</div>

            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
